name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  hive: ^2.2.3
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.1.1 
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/SpaceMono-Regular.ttf
    - assets/fonts/SpaceMono-Bold.ttf
    - assets/fonts/SpaceMono-Italic.ttf
    - assets/fonts/SpaceMono-BoldItalic.ttf
    - assets/images/sliver_app_bar_bg.png

scripts:
  build: dart run build_runner build
  watch: dart run build_runner watch